In [2]:
import numpy as np

width_block_count = 6
height_block_count = 4

# print(round((h-1)/height_block_count)*height_block_count) #664
# print(round((w-1)/width_block_count)*width_block_count) #996
def slice_matrix(shape, threshold=0.5):
    random_matrix = np.random.normal(-0.3, 1, size=shape)
    rounded_matrix = (random_matrix>threshold).astype(int)
    return rounded_matrix

## 因為不想其中一欄或一列都是「空白」，所以避開其中一欄或一列是「1」的情形

def revised_slice_matrix(shape, threshold=0.5):
    while True:
        random_matrix = np.random.normal(-0.3, 1, size=shape)
        rounded_matrix = (random_matrix>threshold).astype(int)
        #if not np.any(np.sum(rounded_matrix, axis=0) == shape[0]) and not np.any(np.sum(rounded_matrix, axis=1) == shape[1]):
        #這個條件式是以免其中一欄或一列都是「1」
        col_sums = np.sum(rounded_matrix, axis=0)
        row_sums = np.sum(rounded_matrix, axis=1)
        if not np.any(row_sums==shape[1]) and not np.any(col_sums==shape[0]) and np.any(rounded_matrix):
            #再加上至少一個元素是「1」
            return rounded_matrix

def find_indices_of_ones(matrix):
    # 使用 np.where 找到矩陣中值為1的元素的索引
    indices = np.where(matrix == 1)
    
    # 將索引以 tuple 的形式返回，每個 tuple 包含一個元素的索引
    return list(zip(indices[0], indices[1]))


# s_matrix = slice_matrix((height_block_count, width_block_count))
s_matrix = revised_slice_matrix((height_block_count, width_block_count))
idxs = find_indices_of_ones(s_matrix)
print(s_matrix)
print(idxs)

[[0 0 0 0 0 1]
 [0 0 0 0 1 1]
 [0 0 0 0 0 1]
 [0 0 0 1 0 0]]
[(0, 5), (1, 4), (1, 5), (2, 5), (3, 3)]


In [10]:
# ------------------ 一開始的版本 -------------------# 

import numpy as np

width_block_count = 6
height_block_count = 4

def slice_matrix(shape, threshold=0.5):
    random_matrix = np.random.rand(*shape)
     #在Python中，*被用作解包（unpacking）運算符。當它放在一個iterable（如列表或元組）前面時，它將這個iterable解包成單獨的元素，然後將這些元素作為單獨的參數傳遞給函數或操作符。
    rounded_matrix = (random_matrix>threshold).astype(int)
    return rounded_matrix


def find_indices_of_ones(matrix):
    # 使用 np.where 找到矩陣中值為1的元素的索引
    indices = np.where(matrix == 1)
    
    # 將索引以 tuple 的形式返回，每個 tuple 包含一個元素的索引
    return list(zip(indices[0], indices[1]))


s_matrix = slice_matrix((height_block_count, width_block_count))
idxs = find_indices_of_ones(s_matrix)
print(s_matrix)
print(idxs)

[[0 1 0 1 1 1]
 [0 0 1 1 1 1]
 [1 1 1 1 0 1]
 [1 0 0 0 0 0]]
[(0, 1), (0, 3), (0, 4), (0, 5), (1, 2), (1, 3), (1, 4), (1, 5), (2, 0), (2, 1), (2, 2), (2, 3), (2, 5), (3, 0)]


In [2]:
import cv2

def crop_img(original_img_path, result_img_path):
    img = cv2.imread(original_img_path, -1)
    h, w = img.shape[:2] #667 1000

    h_part = round((h-1)/height_block_count)
    w_part = round((w-1)/width_block_count)

    result = np.ones(((h_part)*height_block_count-2, (w_part)*width_block_count-2, 3), dtype=np.uint8)*255
    #result[:h, :w] = img

    for i in range(height_block_count):
        for j in range(width_block_count):
            y_start = i*h_part
            y_end = (i+1)*h_part
            x_start = j*w_part
            x_end = (j+1)*w_part

            if (i, j) in idxs:
                continue
                #result[y_start:y_end, x_start:x_end] =  [255, 255, 255]
            else:
                tag = img[y_start:y_end-2, x_start:x_end-2]
                result[y_start:y_end-2, x_start:x_end-2 ] = tag

    # tag = img[400:600, 300:500]  #剪其中一塊
    # img[0:200, 350:550] = tag #把上面的片段放在圖片中

    cv2.imshow('Image', result)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    # cv2.imwrite(result_img_path, result)

crop_img('assets/hw2_pic1.jpg', 'results/hw2_output.jpg')
    

In [4]:
import cv2

def crop_img_o(original_img_path, result_img_path):
    img = cv2.imread(original_img_path, -1)
    h, w = img.shape[:2] #667 1000

    h_part = round((h-1)/height_block_count)
    w_part = round((w-1)/width_block_count)

    result = np.ones(((h_part)*height_block_count-2, (w_part)*width_block_count-2, 3), dtype=np.uint8)*255
    #result[:h, :w] = img

    for i in range(height_block_count):
        for j in range(width_block_count):
            y_start = i*h_part
            y_end = (i+1)*h_part
            x_start = j*w_part
            x_end = (j+1)*w_part

            tag = img[y_start:y_end-2, x_start:x_end-2]
            result[y_start:y_end-2, x_start:x_end-2 ] = tag

    cv2.imshow('Image', result)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    # cv2.imwrite(result_img_path, result)

crop_img_o('assets/hw2_pic1.jpg', 'results/hw2_output_o.jpg')
    

In [ ]:
#------------- 第一版本 ----------- #
# import cv2
# img = cv2.imread('assets/hw2_pic1.jpg', -1)
# h, w = img.shape[:2] #667 1000

# h_part = round((h-1)/height_block_count)
# w_part = round((w-1)/width_block_count)


# for i in range(height_block_count):
#     for j in range(width_block_count):
#         if (i, j) in idxs:
#             img[int(i*h_part):int((i+1)*h_part)-1, int(j*w_part):int((j+1)*w_part)-1] =  [255, 255, 255]
#         else:
#             tag = img[int(i*h_part):int((i+1)*h_part)-2, int(j*w_part):int((j+1)*w_part)-2]
#             img[int(i*h_part):int((i+1)*h_part)-2, int(j*w_part):int((j+1)*w_part)-2 ] = tag

# # tag = img[400:600, 300:500]  #剪其中一塊
# # img[0:200, 350:550] = tag #把上面的片段放在圖片中

# cv2.imshow('Image', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

